# Generated by Django 6.0.3 on 2026-04-02 18:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(9999)])),
                ('plot', models.TextField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('it', 'Italian'), ('jp', 'Japanese'), ('kr', 'Korean'), ('?', 'Other Languages')], default='en', max_length=10)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='How long the movie is (in minutes)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ManyToManyField(blank=True, related_name='movies', to='films.genre')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-year', 'movie_title'],
            },
        ),
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('person_role', models.CharField(choices=[('a_m', 'Actor'), ('a_f', 'Actress'), ('d', 'Director'), ('p', 'Producer'), ('c', 'Composer'), ('w', 'Writer')], default='a_m', max_length=20)),
                ('character_name', models.CharField(blank=True, help_text='Character name if applicable.', max_length=255, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='films.movie')),
            ],
            options={
                'verbose_name': 'Cast Member',
                'verbose_name_plural': 'Cast Members',
                'ordering': ['person_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('movie_title', 'year', 'director'), name='unique_movie'),
        ),
    ]
