# Generated by Django 6.0.3 on 2026-04-02 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='avatar',
            new_name='profile_avatar',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='bio',
            new_name='profile_bio',
        ),
        migrations.AddField(
            model_name='appuser',
            name='favourite_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fans', to='films.genre'),
        ),
    ]
