# Generated by Django 6.0.3 on 2026-04-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_avatar_appuser_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_avatars/'),
        ),
    ]
