# Generated by Django 6.0.3 on 2026-04-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_profile_avatar'),
        ('accounts', '0004_create_user_groups'),
    ]

    operations = [
    ]
