# Generated by Django 6.0.3 on 2026-04-02 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField(help_text='Give your watchlist a name.', max_length=255)),
                ('list_description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Public watchlists are visible to all users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Your thoughts on why you want to see the movie.', null=True)),
                ('is_watched', models.BooleanField(default=False, help_text="Once you've seen the movie, mark it as watched.")),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='films.movie')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='watchlists.watchlist')),
            ],
            options={
                'verbose_name': 'Watchlist Entry',
                'verbose_name_plural': 'Watchlist Entries',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listed_movies',
            field=models.ManyToManyField(blank=True, related_name='watchlists', through='watchlists.WatchlistEntry', to='films.movie'),
        ),
        migrations.AddConstraint(
            model_name='watchlistentry',
            constraint=models.UniqueConstraint(fields=('watchlist', 'movie'), name='unique_movie_per_watchlist'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('list_owner', 'list_title'), name='unique_watchlist_title_per_user'),
        ),
    ]
